### ISSUE TITLE
Need some simple code example.

### ISSUE THREAD

**Issue by zydjohnHotmail** [Dynaruid/TesseractCSharp#1]
Hi,
I want to use your repo to do very simple OCR job, for one png image: "C:\Images\1.png", there is only 1 number inside the picture, for example: it is "1".
How can I write some code just recognize one number?
I look at your example code, I think it is way more complicated than what I want to do: 
try
{
    using var engine = new TesseractEngine(basePath + @"/tessdata", "kor+eng", EngineMode.Default);
    using var img = Pix.LoadFromFile(testImagePath);
    // For images like receipts, you should use PageSegMode.SparseText.
    // using var page = engine.Process(img, pageSegMode: PageSegMode.SparseText);
    using var page = engine.Process(img, pageSegMode: null);

    var text = page.GetText();
    Console.WriteLine("Mean confidence: {0}", page.GetMeanConfidence());

    Console.WriteLine("Text (GetText): \r\n{0}", text);
    Console.WriteLine("Text (iterator):");
    using var iter = page.GetIterator();
    iter.Begin();

    //한번은 반복
    do
    {
        do
        {
            do
            {
                do
                {
                    if (iter.IsAtBeginningOf(PageIteratorLevel.Block))
                    {
                        Console.WriteLine("<BLOCK>");
                    }

                    Console.Write(iter.GetText(PageIteratorLevel.Word));
                    Console.Write(" ");

                    if (iter.IsAtFinalOf(PageIteratorLevel.TextLine, PageIteratorLevel.Word))
                    {
                        Console.WriteLine();
                    }
                } while (iter.Next(PageIteratorLevel.TextLine, PageIteratorLevel.Word));

                if (iter.IsAtFinalOf(PageIteratorLevel.Para, PageIteratorLevel.TextLine))
                {
                    Console.WriteLine();
                }
            } while (iter.Next(PageIteratorLevel.Para, PageIteratorLevel.TextLine));
        } while (iter.Next(PageIteratorLevel.Block, PageIteratorLevel.Para));
    } while (iter.Next(PageIteratorLevel.Block));
}

=> Please show me the code, I need only recognize one number from one image file. Not using any other complicated data structure.
Thanks,

**Comment by Dynaruid** [comment]
Hello. First of all, I apologize for the delayed response.

If you want to perform OCR on images containing single-digit numbers, you can try using 
```
engine.SetVariable("tessedit_char_whitelist", "0123456789"). 
```
Also, if you have a model for languages other than English, the accuracy might be lower, so it's better to specify 
```
using var engine = new TesseractEngine(basePath + @"/tessdata", "eng", EngineMode.Default);
```
 My repository is just an improvement on binding Tesseract to .NET, and the performance and functionality of OCR are unchanged from the original Tesseract. Therefore, if there are any issues with OCR methods, I think it's better to refer to the original Tesseract project.

Below are some settings you can try for recognizing numeric images.
![803](https://github.com/Dynaruid/TesseractCSharp/assets/160819058/b1379f26-07c5-4aa4-a31c-5a9fa826cf40)
 Even though the image is focused on numbers, unnecessary characters might be mixed in the background. Using 
 ```
 using var page = engine.Process(img, pageSegMode: null); 
 ```
in this case might not recognize the numbers properly. In such cases, try using 
using var page = engine.Process(img, pageSegMode: PageSegMode.SingleWord);. Below is a simple example code for this situation:
 ```
 string basePath = AppContext.BaseDirectory;
var testImagePath = basePath + "/images/image1.jpg";
using var engine = new TesseractEngine(basePath + @"/tessdata", "eng", EngineMode.Default);
using var img = Pix.LoadFromFile(testImagePath);
engine.SetVariable("tessedit_char_whitelist", "0123456789");
using var page = engine.Process(img, pageSegMode: PageSegMode.SingleWord);

var text = page.GetText();
Console.WriteLine(text);
Console.WriteLine("Press any key...");
Console.ReadKey();
 ```
 Let's look at another situation.
![num07](https://github.com/Dynaruid/TesseractCSharp/assets/160819058/1b80350a-a535-4096-9e15-8ca7fca8a964)
 In this case, since the characters are spread throughout the image, it's better to use PageSegMode.SparseText. Below is the example code:
 ```
 string basePath = AppContext.BaseDirectory;
var testImagePath = basePath + "/images/image2.jpg";

using var engine = new TesseractEngine(basePath + @"/tessdata", "eng", EngineMode.Default);
using var img = Pix.LoadFromFile(testImagePath);

engine.SetVariable("tessedit_char_whitelist", "0123456789");
using var page = engine.Process(img, pageSegMode: PageSegMode.SparseText);
var text = page.GetText();
Console.WriteLine(text);
Console.WriteLine("Press any key...");
Console.ReadKey();
 ```
 Also, be careful not to include any distinct lines or borders between the numbers.
